Repository iver-wharf/wharf-core, pull requests merged in 2021-07, with the labels that each got.

#10 pkg/logger
  CHANGELOG.md
  README.md
  THIRD_PARTY_NOTICES.md
  assets/consolepretty.jpg
  go.mod
  go.sum
  internal/traceutil/traceutil.go
  pkg/logger/README.md
  pkg/logger/consolejson/doc.go
  pkg/logger/consolejson/json.go
  pkg/logger/consolejson/json_example_test.go
  pkg/logger/consolejson/json_test.go
  pkg/logger/consolepretty/doc.go
  pkg/logger/consolepretty/pretty.go
  pkg/logger/consolepretty/pretty_example_test.go
  pkg/logger/context.go
  pkg/logger/doc.go
  pkg/logger/event.go
  pkg/logger/level.go
  pkg/logger/level_example_test.go
  pkg/logger/logger.go
  pkg/logger/logger_example_test.go
  pkg/logger/mock.go
Labels: enhancement

#15 Added Event.WithStringer
  CHANGELOG.md
  pkg/logger/event.go
Labels: enhancement

#14 Added logger.ParseLevel
  pkg/logger/level.go
  pkg/logger/level_test.go
Labels: enhancement

#16 Fixed example test name config_test.ExampleNewBuilder
  CHANGELOG.md
  pkg/config/config_example_test.go
Labels: enhancement

#13 Added WithStringf to Event
  CHANGELOG.md
  pkg/logger/event.go
Labels: enhancement

#12 Added problem util funcs from iver-wharf/wharf-api-client-go#12
  CHANGELOG.md
  pkg/ginutil/writeproblem.go
  pkg/problem/response.go
  pkg/problem/response_example_test.go
  pkg/problem/response_test.go
  pkg/strutil/strutil.go
  pkg/strutil/strutil_example_test.go
Labels: enhancement

#17 Added new error response functions
  CHANGELOG.md
  pkg/ginutil/writeproblem.go
Labels: enhancement

#20 Added SetLevel & SetLevelScoped
  CHANGELOG.md
  pkg/logger/consolejson/json.go
  pkg/logger/consolepretty/pretty.go
  pkg/logger/context.go
  pkg/logger/event.go
  pkg/logger/level.go
  pkg/logger/logger.go
  pkg/logger/logger_test.go
  pkg/logger/mock.go
Labels: enhancement

#18 Added environment binding
  CHANGELOG.md
  internal/testutil/testutil.go
  pkg/env/env.go
  pkg/env/env_example_test.go
  pkg/env/env_test.go
Labels: enhancement

#11 GIN & GORM logging integration
  CHANGELOG.md
  pkg/ginutil/logger.go
  pkg/ginutil/logger_example_test.go
  pkg/gormutil/logger.go
  pkg/gormutil/logger_example_test.go
  pkg/gormutil/logger_test.go
Labels: enhancement

#21 Added PR templates
  .github/.remarkrc
  .github/PULL_REQUEST_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE/release.md
  package.json
Labels: documentation

#19 Added ginutil.RecoverProblem
  pkg/ginutil/recover.go
  pkg/ginutil/recover_example_test.go
Labels: enhancement

#22 Release v1.0.0
  CHANGELOG.md
Labels: release
